  $(document).ready(function(){
    $("#me").click(function(){
      $("#mean").show();
      $("#mode,#median,#range,#standard,#covariance,#hamming,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#mo").click(function(){
      $("#mode").show();
      $("#mean,#median,#range,#standard,#covariance,#hamming,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#med").click(function(){
      $("#median").show();
      $("#mode,#mean,#range,#standard,#covariance,#hamming,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#r").click(function(){
      $("#range").show();
      $("#mode,#median,#mean,#standard,#covariance,#hamming,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#st").click(function(){
      $("#standard").show();
      $("#mode,#median,#range,#mean,#covariance,#hamming,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#co").click(function(){
      $("#covariance").show();
      $("#mode,#median,#range,#standard,#mean,#hamming,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#h").click(function(){
      $("#hamming").show();
      $("#mode,#median,#range,#standard,#covariance,#mean,#correlation,#correlation,#cosine,#jaccard").hide();
    });
    $("#cor").click(function(){
      $("#correlation").show();
      $("#mode,#median,#range,#standard,#covariance,#hamming,#mean,#cosine,#jaccard").hide();
    });
    $("#cos").click(function(){
      $("#cosine").show();
      $("#mode,#median,#range,#standard,#covariance,#hamming,#correlation,#correlation,#mean,#jaccard").hide();
    });
    $("#j").click(function(){
      $("#jaccard").show();
      $("#mode,#median,#range,#standard,#covariance,#hamming,#correlation,#correlation,#cosine,#mean").hide();
    });
  });